/**
 * Csrs.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PortalAccount { 
    partyGuid?: string;
    bCeIDGuid: string;
    firstName: string;
    middleName?: string | null;
    lastName: string;
    preferredName?: string | null;
    dateOfBirth: string;
    gender: string;
    addressStreet1?: string | null;
    addressStreet2?: string | null;
    city?: string | null;
    province?: string | null;
    postalCode?: string | null;
    homePhone?: string | null;
    workPhone?: string | null;
    cellPhone?: string | null;
    email: string;
    optOutElectronicDocuments?: boolean;
    identity?: string | null;
    referral?: string | null;
}

