// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Csrs.Interfaces.Dynamics.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of ssg_ijssbccourtlocation
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.ssg_ijssbccourtlocationCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMssgIjssbccourtlocationCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMssgIjssbccourtlocationCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMssgIjssbccourtlocationCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMssgIjssbccourtlocationCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMssgIjssbccourtlocationCollection(IList<MicrosoftDynamicsCRMssgIjssbccourtlocation> value = default(IList<MicrosoftDynamicsCRMssgIjssbccourtlocation>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMssgIjssbccourtlocation> Value { get; set; }

    }
}
